### ISSUE TITLE
no save figure option

### ISSUE THREAD

**Issue by menchant** [djwooten/synergy#3]
great tool for synergy analysis. I'm wondering how to export figures as png or pdf etc. after the model.plot_heatmap.

**Comment by genevievebo** [comment]
You can pass a filename to plot_heatmap() via the parameter `fname`.  For example,  
`model.plot_heatmap(d1, d2, fname='figure.png')`

plot_heatmap uses matplotlib to create the graph. Passing a filename will use the matplotlib.pyplot function `plt.savefig()`.  I'm using the package synergy v.0.4.1.

**Comment by menchant** [comment]
> You can pass a filename to plot_heatmap() via the parameter `fname`. For example,
> `model.plot_heatmap(d1, d2, fname='figure.png')`
> 
> plot_heatmap uses matplotlib to create the graph. Passing a filename will use the matplotlib.pyplot function `plt.savefig()`. I'm using version 0.4.1.

thank you very much!
