### ISSUE TITLE
Plot title in plot_surface_plotly

### ISSUE THREAD

**Issue by maikhel** [djwooten/synergy#4]
Hello, I'm using your package (works really great, thanks!) and I need to set custom titles for surface plots. Right now the title is the same as file name, which looks to be done here:
```
    title = ""
    if fname is not None:
        title = fname
```
Would it be possible to add one more parameter to `plot_surface_plotly` function, eg `plot_title`?

**Comment by djwooten** [comment]
I'm glad the package is working well for you! You are right about the title. I just updated plot_surface_plotly() and plotly_isosurfaces() to accept "title" as a keyword argument, so you can do

`plot_surface_plotly(d1, d2, E, title="Whatever you want")`

This is in the 0.4.4 update, both on github and pip. Please let me know if you have any problems with it.

**Comment by maikhel** [comment]
Works like a charm, thank you!
