### ISSUE TITLE
Wrong test

### ISSUE THREAD

**Issue by thomasgaudelet** [djwooten/synergy#5]
Thanks for the package, it's very helpful. I think I have spotted an error though here

https://github.com/djwooten/synergy/blob/77e666c3b820bb1639105db221235d5af7e8e28b/src/synergy/combination/loewe.py#L71

I believe the test here should be:
`if self.variant.startswith("delta"):`
to be compatible with _delta_synergyfinder_ and _delta_hsa_

Cheers,
Thomas

**Comment by djwooten** [comment]
Thanks for catching that, you are quite right. I have fixed this and pushed to v0.4.5, available on both github and pip.
