### ISSUE TITLE
Effect Axis in plot_surface_plotly

### ISSUE THREAD

**Issue by DJuarez10** [djwooten/synergy#6]
Thank you for this synergy package! I want to visually compare the effects of drugs across a number of different cell lines. Could you include a way to set the effect axis (and the color gradient) from 0-1? It currently autoscales to the input data.

**Comment by djwooten** [comment]
Hi, you can set the effect axis using the zlim keyword argument, and the color gradient using vmin and vmax. Does `plot_surface_plotly(d1, d2, E, zlim=(0,1), vmin=0, vmax=1)` accomplish what you want?

**Comment by DJuarez10** [comment]
That is exactly what I'm looking for. I tried a few variations of this that didn't end up working for me but I realize the error was on my end. Thank you again!

**Comment by djwooten** [comment]
Great! Thanks for reaching out, and if you have any other issues, please don't hesitate!
