### ISSUE TITLE
What should we do with replicates?

### ISSUE THREAD

**Issue by genevievebo** [djwooten/synergy#8]
What should we do if we have replicates? The parametric models should handle well the replicates.  However, for the non parametric models (such as Bliss), replicates are not handled directly.  Do you recommend that we aggregate (mean, median) the replicates for the non parametric models but not for the parametric ones?  Thanks!

**Comment by djwooten** [comment]
Thanks for considering this case. I agree with your proposed solution, and merged #7. I also think this solution should be used for plot_surface_plotly(), which would have the same problem. I'll add that and push, along with a new version number for pip.
